config/routes.rb
Kidsland::Application.routes.draw do

  resources :people

  get "pages/home"
  get "pages/print_page"
  match "view_page" => 'pages#view_page', :as => 'view_page'

  post "headshot/capture" => 'headshot#capture', :as => :headshot_capture
  devise_for :users
  resources :resume
  root :to => 'resume#show'

end

app/models/headshot_photo.rb
class HeadshotPhoto < ActiveRecord::Base
  attr_accessible :description, :image_content_type, :image_file_name, :image_file_size, :image_updated_at

  belongs_to :capturable, :polymorphic => true
  #has_one :person
  
  has_attached_file :image, :styles => { :medium => "200x200>", :thumb => "101x129#" }
end

app/models/person.rb
class Person < ActiveRecord::Base
  attr_accessible :first_name, :last_name, :nationality, :sex, :dob, :age, :school_number, :school_type, :klass, :headshot_photo_id
  #belongs_to :headshot_photo
  has_many :headshot_photos, :as => :capturable
 # has_and_belongs_to_many :variants
  after_create :add_photo #, :clear

  def clear
    Person.where(["created_at < ?", 2.days.ago]).delete_all 
  end
 
  def add_photo
    if HeadshotPhoto.all.size > 0
      self.headshot_photos << HeadshotPhoto.all.last
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  #before_filter :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
 # before_filter :authenticate_user!
  helper :headshot
  
  def home
  
  end

  def print_page
    render :layout => false
  end
  
  def view_page
   cookies[:person_id] = params[:person_id]
   render 'resume/print_resume'
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    #@people = Person.all
    @q = Person.search(params[:q])
    @people = @q.result(distinct: true).paginate(:page => params[:page], :per_page => 50)
  end

  def show
    @person = Person.find(params[:id])
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(params[:person])
    if @person.save
      redirect_to @person, :notice => "Successfully created person."
    else
      render :action => 'new'
    end
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])
    if @person.update_attributes(params[:person])
      redirect_to @person, :notice  => "Successfully updated person."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @person = Person.find(params[:id])
    @person.destroy
    redirect_to people_url, :notice => "Successfully destroyed person."
  end
end

app/controllers/resume_controller.rb
class ResumeController < ApplicationController
  helper :headshot
  # before_filter :authenticate_user!
  include Wicked::Wizard
  
  steps :start_page, :make_photo, :info,  :print_resume


 def show
  #  @user = current_user
  case step
  when :info
    @person = Person.create
    cookies[:person_id] = @person.id
  end  
   render_wizard
 end

 def update
  @person = Person.find(cookies[:person_id])
  case step
    when :info
      @person.attributes = params[:person]
    end
     
   render_wizard @person
  end

#def create

#  case step
# when :info
#   @person = Person.create
# end 
# 
#   redirect_to wizard_path(steps.first, :product_id => @product.id)
# end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/resume_helper.rb
module ResumeHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/variants_helper.rb
module VariantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= javascript_include_tag "application" %>
    
   
    <title><%= content_for?(:title) ? yield(:title) : "Kid-Ландія" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
    
     </head>
  <body>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Kid-Ландія</a>
          <div class="container nav-collapse">
            <ul class="nav">
                <li class="divider-vertical"><a href="/"><i class="icon-file"></i>Старт</a></li>
              <% if user_signed_in? %>
                <li class="divider-vertical"><a href="/services"><i class="icon-question-sign"></i>Вопросы/Профессии</a></li>
                <li class="divider-vertical"><a href="/people"><i class="icon-th-list"></i>Анкеты</a></li>
                <li class="divider-vertical"><a href="<%= edit_user_registration_path(:method => :get)%>"><i class="icon-user"></i><%= current_user.email %></a></li>
                <li class="divider-vertical"><a href="<%=  destroy_user_session_path%>" data-method="delete"><i class="icon-off"></i>Выход</a></li>
            <% end %>
            </ul>
 
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container well" style="background-color:white; ">
      <div class="content " >
        <div class="row">
          <div class="span12">
              <%= yield %>
            </div>
            <div class="span3">

<%
=begin
%>
              <div class="well sidebar-nav">
                <h3>Sidebar</h3>
                <ul class="nav nav-list">
                  <li class="nav-header">Sidebar</li>
                  <li><%= link_to "Link1", "/path1"  %></li>
                  <li><%= link_to "Link2", "/path2"  %></li>
                  <li><%= link_to "Link3", "/path3"  %></li>
                </ul>
              </div><!--/.well -->
 
<%
=end
%>
            </div><!--/span-->
        </div><!--/row-->
      </div><!--/content-->

      <footer class="pagination-centered">
        <p>&copy; Kid-Ландія 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%#= javascript_include_tag "application" %>
<script>
     // To attach Backstrech as the body's background
     //$.backstretch("http://www.freefever.com/stock/cute-scenery-background-wallpapers-cartoon-wallpaper.jpg");
 //     $.backstretch("<%= asset_path("background.jpg")%>");   
</script>

  </body>
</html>

app/views/pages/home.html.erb
<h1>Headshot Demo</h1>

<%= headshot_default_config(Rails.application.config.session_options[:key], headshot_capture_path) %>

<%= headshot_camera %>
<br/>

<%= headshot_snap_button  %>
<button name="button" onclick="headshot.configure()" type="submit">Configure</button>

app/views/pages/print_page.html.erb
<style> 

body * {
    visibility:hidden;
  margin: 0px;
}

body {
  margin: 0px;
  width: 310px;
  height: 194px;

}
  #driver_id * {
    visibility:visible;
  }
  @media print {
  body * {
    visibility:hidden;
  }
  body {
    margin: 0px;
    width: 310px;
    /*height: 194px;*/
    height: 388px;
  }
  
  #driver_id * {
    visibility:visible;
  }
  #driver_id {
    left:0;
    top:0;
  }
}
</style>
<% @person = Person.find(cookies[:person_id]) %>
<div id="driver_id" style="position: relative; max-width:310px; height:388px;" >
  <%= image_tag "front.jpg" , :size=>"310x194" %>
  <% if @person.headshot_photos.size >0  %>
    <%= image_tag "/headshots/#{@person.headshot_photos.last.image_file_name}" ,
    :size => "87x111", :class=>"img-rounded", :style=>" position: absolute; left: 27px; top: 43px; " %>
  <% end %>
  <h6 style=" position: absolute; top: 58px; left: 146px;"> <%= @person.last_name %> </h4>
  <h6 style=" position: absolute; top: 89px; left: 146px;"> <%= @person.first_name  %> </h4>
  <h6 style=" position: absolute; top: 122px; left: 147px;"> <%= @person.dob.strftime("%d-%m-%Y") %> </h4>
  <h6 style=" position: absolute; top: 145px; left: 146px;"> <%= (Time.now + 5.years).to_date.strftime("%d-%m-%Y") %> </h4>

<hr>
<%= image_tag "back.jpg" , :size=>"310x194" %>
</div> 

app/views/people/_form.html.erb
<%= form_for @person, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :first_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :first_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :last_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :last_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :sex, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :sex, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :dob, :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :dob, :class => 'date_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :school_number, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :school_number, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :school_type, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :school_type, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :klass, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :klass, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group"  style="display:none;">
    <%= f.label :headshot_photo, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :headshot_photo, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit "Сохранить", :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                people_path, :class => 'btn' %>
  </div>
<% end %>

app/views/people/edit.html.erb
<%- model_class = Person -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/people/index.html.erb
<%- model_class = Person -%>
<div class="page-header">
 <h5> Список резюме </h5>
</div>

<%= search_form_for @q do |f| %>

  <%= f.label :last_name_cont %>
  <%= f.search_field :last_name_cont %>

  <%= f.submit %>
<% end %>
<table class="table table-striped">
  <thead>
  </thead>
  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= link_to person.id, person_path(person) %></td>
        <td><%= person.first_name %></td>
        <td><%= person.last_name %></td>
        <td><%=l person.created_at %></td>
        <td>
          <%= link_to "Открыть",
            view_page_path(:person_id => person.id), :class => 'btn btn-mini' %>
          <%= link_to "Удалить",
                      person_path(person),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @people %>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_person_path,
            :class => 'btn btn-primary' %>

app/views/people/new.html.erb
<%- model_class = Person -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/people/show.html.erb
 <script>  
  $(document).ready(function() {
    $(".btnPrint").printPage(
    {
      url: "/resume/print_resume",
      attr: "href",
      message:"Идет печать ..."
}
    );
  });
</script>

<div class="row">
  <div class="span4 offset4">
  <h2 class="muted"> Резюме </h2>
</div>
</div>
<%# @person = Person.last %>
<%- model_class = Person -%>
<hr>

<div class="alert alert-info">
  <h4><%=t '.title', :default => "Персональная ифнормация:" %></h4>
</div>
<div class="row" >
 
  <div class="span8">
    <h4>
    <dl class="dl-horizontal">
    <dt><strong>Имя:</strong></dt>
    <dd><%= @person.first_name %></dd>
    <dt><strong>Фамилия: </strong></dt>
    <dd><%= @person.last_name %></dd>
    <dt><strong>Пол:</strong></dt>
    <dd><%= @person.sex %></dd>
    <dt><strong>№:</strong></dt>
    <dd><%= @person.school_number %></dd>
    <dt><strong>Тип:</strong></dt>
    <dd><%= @person.school_type %></dd>
    <dt><strong>Класс:</strong></dt>
    <dd><%= @person.klass %></dd>
  </dl>
  </h4>
  </div>
  <div class="span4" >
 <a href="#" class="thumbnail">
                  <img data-src="holder.js/260x180" alt="">
                </a>
  </div>

</div>
<hr>
<div class="alert alert-info">
  <h4><%=t '.title', :default => "Интересы:" %></h4>
</div>
<div class="row ">
  <div class="span6 offset3 muted">
    <ul>
      <% @person.variants.each do |variant| %> 
        <li> <h5> <%= variant.text %> </h5> </li>
      <% end %>
    </ul>
  </div>
</div>

<hr>
<div class="alert alert-info">
  <h4><%=t '.title', :default => "Рекомендуемая сфера деятельности:" %></h4>
</div>
<div class="row ">
  <div class="span6 offset3 muted">
    <h5> <%= Service.first.name %> </h5>
  </div>
</div>

<hr>
<div  class="alert alert-info">
  <h4><%=t '.title', :default => "Рекомендуемые профессии КидЛандии:" %></h4>
</div>
<div class="row ">
  <div class="span6 offset3 muted ">
    <%
    list=""  
    @person.variants.each do |variant|
      variant.jobs.each do |job|
        list << " #{job.name} "
      end
    end
    %>
    <% list.split(" ").each do |l|%>
      <li> <h5> <%= l %></h5> </li>
    <% end %>
      <h4> <%#= list %></h4>
  </div>
</div>
<hr />

<div class="form-actions">
  <a class="btnPrint btn btn-primary btn-large" href='iframes/iframe.html' id="print_link">Распечатать</a>
  <%= link_to "Назад",
    people_path, :class => 'btn'  %>
</div>

app/views/resume/answer_question.html.erb
<h1>  Сдесь будут вопросы ... </h1>
<br  />
  <hr>
  <p>
    <%= link_to 'Далее', next_wizard_path, :class=> "btn btn-primary btn-large pull-right"%>
  </p>

app/views/resume/info.html.erb
<div class="row">
  <div class="span4 offset4" >
    <%= image_tag("mickey.jpg" , :size=>"250x250") %>
  </div>
</div>

  <hr>
  <div class="alert alert-info">
    <h4> Введіть інформацію про себе: </h4>
  </div>
<hr>

<div class="row">
  <div class="span6 offset3">
<%= form_for @person,  url: wizard_path,  :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label "Введіть своє ім'я:", :class => 'control-label' %> 
    <div class="controls">
      <%= f.text_field :first_name, :class => 'text_field' , :required => true %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label "Введіть своє прізвище:", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :last_name, :class => 'text_field' , :required => true%>
    </div>
  </div>
   <div class="control-group" style="">
    <%= f.label "Вкажіть громадянство:", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :nationality, :class => '' ,  :required => true%>
    </div>
  </div>
 <div class="control-group" style="">
    <%= f.label "Вкажіть дату народження:", :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :dob,
        :start_year => Time.now.year - 20,
        :end_year => Time.now.year,
        :use_month_names=>["Січень", "Лютий", "Березень", "Квітень", "Травень", "Червень",
                                                 "Липень", "Серпень", "Вересень", "Жовтень", "Листопад", "Грудень"] ,  :required => true %>
    </div>
  </div>

<hr>
 

</div>
</div>
 <div class="form-actions  pagination-centered">
    <%= f.submit "Далі", :class => 'btn btn-primary btn-large ' %>
  </div>
  <% end %>

app/views/resume/make_photo.html.erb
<script language="JavaScript"> 
var customCameraHooks = {
  onComplete: function(response) {
  $('#next').css('visibility','visible');
}
};
</script>
<div class="alert alert-info">
<h2>Дивись у камеру, посміхнись і нажми кнопку "Фото" коли будеш готовий ☺</h2>
</div>
<hr>
<div class="pagination-centered" >

<%= headshot_default_config(Rails.application.config.session_options[:key], headshot_capture_path, :on_complete => "customCameraHooks.onComplete") %>

<%= headshot_camera(width = 303, height = 390)%>

<br/>
<hr>
<button name="button" onclick="headshotHandlers.snap()" type="submit" class="btn btn-success btn-large">Фото</button>
<button name="button" onclick="headshot.configure()" type="submit">Настройка</button>

</div>
<br  />
<hr>
  <div class="form-actions pagination-centered" >
    <%= link_to 'Далі', next_wizard_path,:id=>"next", :class=> " btn btn-primary btn-large" , :style=>"visibility:hidden;"%>
  </div>

app/views/resume/print_resume.html.erb
 <script>  
  $(document).ready(function() {
    $(".btnPrint").printPage(
    {
      url: "/pages/print_page",
      attr: "href",
      message:"Идет печать ..."
}
    );
  });
</script>
<div id="print_page"  >
<% @person = Person.find(cookies[:person_id]) %>
<%- model_class = Person -%>
<div class="alert alert-info">
  <h4><%=t '.title', :default => "Посвідчення Водія :" %></h4>
</div>



<div id="driver_id" style="position: relative; width:323px; height:204px;" >
  <%= image_tag "front.jpg" , :size=>"323x204" %>
  <% if @person.headshot_photos.size >0  %>
    <%= image_tag "/headshots/#{@person.headshot_photos.last.image_file_name}" ,
    :size => "91x129", :class=>"img-rounded", :style=>" position: absolute; left: 27px; top: 46px; " %>
  <% end %>
  <h6 style=" position: absolute; top: 52px; left: 146px;"> <%= @person.last_name %> </h4>
  <h6 style=" position: absolute; top: 89px;  left: 146px;"> <%= @person.first_name %> </h4>
  <h6 style=" position: absolute; top: 118px; left: 147px;"> <%= @person.dob.strftime("%d-%m-%Y") %> </h4>
  <h6 style=" position: absolute; top: 141px; left: 146px;"> <%= (Time.now + 5.years).to_date.strftime("%d-%m-%Y") %> </h4>
</div>  


<hr />
  <p class="pagination-centered"> <a class="btnPrint btn btn-primary btn-large" href='iframes/iframe.html' id="print_link">Роздрукувати</a></p>

</div>

app/views/resume/question1.html.erb
<div class=row>
  <div class="span4 offset4" >
    <%= image_tag("http://upload.wikimedia.org/wikipedia/ru/archive/9/98/20121013113115!Mickey_Mouse_in_Steamboat_Willie,_1928.jpg" , :size=>"250x250") %>
  </div>
</div>
<hr>

<% @question = Question.all[0] %>

<div class="alert alert-info">
  <h3> <%= @question.text %> </h3>
</div>
<%= form_tag("/resume/question1" , :method => :put)  do  %>
  <% @question.variants.each do |v| %>
    <label class="radio">
      <%= radio_button_tag(:variant, v.id) %>
      <h4 class="muted"> <%= v.text %> </h4>
    </label>
  <% end %>
  <hr>
  <div class="form-actions pagination-centered">
    <%= submit_tag "Далі" , :class=> " btn btn-primary btn-large"%>
  </div>
<% end %>


<br  />

app/views/resume/question2.html.erb
<div class=row>
  <div class="span4 offset4" >
    <%= image_tag("http://upload.wikimedia.org/wikipedia/ru/archive/9/98/20121013113115!Mickey_Mouse_in_Steamboat_Willie,_1928.jpg" , :size=>"250x250") %>
  </div>
</div>
<hr>
<% @question = Question.all[1] %>

<div class="alert alert-info">
  <h3> <%= @question.text %> </h3>
</div>
<%= form_tag("/resume/question2" , :method => :put)  do  %>
  <% @question.variants.each do |v| %>
    <label class="radio">
      <%= radio_button_tag(:variant, v.id) %>
  <h4 class="muted"> <%= v.text %> </h4>
    </label>
  <% end %>
 <hr>
  <div class="form-actions  pagination-centered">
    <%= submit_tag "Далі" , :class=> " btn btn-primary btn-large"%>
  </div>
<% end %>

app/views/resume/question3.html.erb
<div class=row>
  <div class="span4 offset4" >
    <%= image_tag("http://upload.wikimedia.org/wikipedia/ru/archive/9/98/20121013113115!Mickey_Mouse_in_Steamboat_Willie,_1928.jpg" , :size=>"250x250") %>
  </div>
</div>
<hr>
<% @question = Question.all[2] %>

<div class="alert alert-info">
  <h3> <%= @question.text %> </h3>
</div>
<%= form_tag("/resume/question3" , :method => :put)  do  %>
  <% @question.variants.each do |v| %>
    <label class="radio">
      <%= radio_button_tag(:variant, v.id) %>
      <h4 class="muted">  <%= v.text %>  </h4>
    </label>
  <% end %>
 <hr>
  <div class="form-actions pagination-centered">
    <%= submit_tag "Далі" , :class=> " btn btn-primary btn-large"%>
  </div>
<% end %>

app/views/resume/question4.html.erb
<div class=row>
  <div class="span4 offset4" >
    <%= image_tag("http://upload.wikimedia.org/wikipedia/ru/archive/9/98/20121013113115!Mickey_Mouse_in_Steamboat_Willie,_1928.jpg" , :size=>"200x200") %>
  </div>
</div>
<hr>

<% @question = Question.all[3] %>

<div class="alert alert-info">
  <h3> <%= @question.text %> </h3>
</div> 
<%= form_tag("/resume/question4" , :method => :put)  do  %>
  <% @question.variants.each do |v| %>
    <label class="radio">
      <%= radio_button_tag(:variant, v.id) %>
      <h4 class="muted">  <%= v.text %> </h4>
    </label>
  <% end %>
  <hr>
  <div class="form-actions pagination-centered">
    <%= submit_tag "Далі" , :class=> " btn btn-primary btn-large"%>
  </div>
 <% end %>

app/views/resume/start_page.html.erb
<div class="alert alert-info">
  <div class="row">
    <div class="span8 offset3">
      <h2 > Вітаємо в 
      <strong > Автошколі </strong></h2>
 
<hr>
      </div>
 </div>
</div>
<hr>
<div class="row">
 
    <div class="span4 offset4">
      <%= image_tag("cars.jpg" , :size=>"300x300") %>
    </div>
 
    <div class="span4">
    </div>
    
  </div>
  <br  />
  <hr>
  <div class="form-actions  pagination-centered">
    <%= link_to 'Далі', next_wizard_path, :class=> "btn btn-primary btn-large "%>
  </div>